### ISSUE TITLE
Control seed of RNG and output it on result

### ISSUE THREAD

**Issue by hugoferreira** [fluent-check/fluent-check#139]
Debugging non-deterministic checks is becoming hard, and we sometimes want to replicate a specific case generation. I suggest the following:

1. Allow the user to provide the initial seed for the internal RNG via scenario configuration
2. Return the used seed in the result, so that we can replicate non-deterministic fails, such as the one in #138

**Comment by hugoferreira** [comment]
In the quest to find a seedable RNG, I came across this interesting page: https://observablehq.com/@tidwall/hello-randomness

@ruippeixotog , @arestivo what do you guys think we should favor? Speed or uniformness?

**Comment by arestivo** [comment]
Looking at those images, [xoshiro128](https://prng.di.unimi.it/) looks nice (fast, uniform, and seedable).

**Comment by hugoferreira** [comment]
At 13 ns/op it's also one of the fastest.

**Comment by RuiGuedes** [comment]
@hugoferreira Do you think it is a good idea to mix our arbitraries with others from another library? Despite them being different won't they introduce some confusion?

**Comment by tiagoacastro** [comment]
I was thinking the same thing as @RuiGuedes , what I had in mind was something like Math.random where random float-point values are generated based on a seed for easy reproducibility.

**Comment by hugoferreira** [comment]
> @hugoferreira Do you think it is a good idea to mix our arbitraries with others from another library? Despite them being different won't they introduce some confusion?

Good point; it's a cost-benefit analysis. My main problem in using their _"arbitraries"_ is not really due to confusion, but mostly due to having no idea on how to _shrink_ something that I don't know how it was generated :p That doesn't mean that we shouldn't look to other libraries that already provide seeded RNG. 

Currently we have 8 instances of `Math.random` in the whole project. In order to have consistent seeding, they must all share the same `generator`, scoped by a particular scenario. I'm curious on the implementation...

**Comment by ruippeixotog** [comment]
I'm ok with any RNG. xoshiro128 seems like a good default, but if we want users to be able to provide a `number` seed I'd much rather allow them to provide a `(seed: number) => () => number` generator as an alternative, allowing them to weigh the tradeoffs themselves.
