### ISSUE TITLE
Fix canGenerate in MappedArbitrary

### ISSUE THREAD

**Issue by RuiGuedes** [fluent-check/fluent-check#152]
The current mapped arbitrary uses this code to check if a `pick` can be generated:

```
canGenerate(pick: FluentPick<B>) {
    /* && pick.value === this.f(pick.original) */
    return this.baseArbitrary.canGenerate({value: pick.original, original: pick.original})
  }
```

Well, that's not strictly true in cases such as: 

```
expect(fc.integer(0, 1).map(a => a === 1 ? 'true' : 'false')
      .canGenerate({original: 'true', value: 'true'})).to.be.true
```

Or even more complicated:

```
expect(fc.integer(-10, 0).map(a => Math.abs(a))
      .canGenerate({original: -5, value: -5})).to.be.true // Should be false
```

**Comment by hugoferreira** [comment]
@RuiGuedes can you please change the screenshots to code snippets like:

```typescript
canGenerate(pick: FluentPick<B>) { ... }
```

... otherwise it's not easy to copy-paste examples ;)

**Comment by hugoferreira** [comment]
BTW, although we've been discussing ways of solving this, I've just realised that `FluentPick` should have a generic type in *both* arguments (`original` and and `value`). The `canGenerate` of that `map` should probably statically refuse a `FluentPick` where the original value type doesn't match the base arbitrary type. Something to consider in #137.
